### ISSUE TITLE
Fetching via Microsoft Mail App

### ISSUE THREAD

**Issue by sujit223** [barbushin/php-imap#142]
Thanks for your wonderful package for fetching emails.
I have one issue fetching emails via [Microsoft Mail Application](https://www.microsoft.com/en-us/store/apps/mail-and-calendar/9wzdncrfhvqm) .
Whenever I try to fetch emails sent via this application I get an attachment separately in HTML format and the message body that is being fetched is completely encrypted.
I think that this is a bug in fetching mail. Please help on this issue.

**Comment by daniel-exsyn** [comment]
I'm noticing the same with some messages fetched from Office 365.
Both textPlain & textHtml are null, but one of the attachments is a html file with the message content.

**Comment by daniel-exsyn** [comment]
Appears only to happen with Content-Type: multipart/related messages.

**Comment by commanddotcom** [comment]
Smth is fucked up around lines: [635-640](https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L635-L640)

Either `ifid` should not define the part as attachment or `$partNum` should not required to be `0`.

@daniel-exsyn i have this issue with `multipart/mixed` as well

**Comment by Sebi94nbg** [comment]
@sujit223 @daniel-exsyn @commanddotcom 
Are you still facing this issue with the current latest version 3.0.17?

**Comment by Sebi94nbg** [comment]
Finally I found some time to test this by my own.

This issue seems to be fixed.

I've sent myself an email via the "Microsoft Mail" application and fetched it using php-imap v3.0.24.

The `->textPlain` contained the plain message, the `->textHtml` contained the styled HTML message and no attachments were saved (as expected since the mail did not have any attachment).
