### ISSUE TITLE
Performance improvement, my solution

### ISSUE THREAD

**Issue by j4r3kb** [barbushin/php-imap#154]
Hello,
I'm using this bundle in company project. When I connected mailbox with 18000+ mails in INBOX folder and tried to load them all (don't ask why ;)) it took forever. After some research I learned that mails can be fetched by sequence number or UID. So I extended your Mailbox Class and done the following:

```
public function searchMailbox($criteria = 'ALL') {
    $mailsIds = imap_search($this->getImapStream(), $criteria, SE_FREE, $this->serverEncoding);
    return $mailsIds ? $mailsIds : array();
}
```

SE_FREE instead of SE_UID

and:

```
public function getMailsInfo(array $mailsIds) {
    $mails = imap_fetch_overview($this->getImapStream(), implode(',', $mailsIds), 0);
...
```

0 instead of FT_UID.

Those two changes made execution of imap_fetch_overview ~15 times faster. For example fetching 8000 mails took 90.4 seconds on stock and 5.6 seconds with above changes. I compared the search results (to check if some emails where missed) with both methods and they were same.
However, if given range of emails is fetched for the first time it takes equal time in both cases. Only following fetches are faster with my method.
Could you explain this case for me?

**Comment by Sebi94nbg** [comment]
SE_FREE is usually faster, because it's just an incremental ID starting at 1 while SE_UID is the unique ID for each email, which needs to be retrieved somewhere first. Retrieving the UID takes usually some time and depending on the server, it's sometimes faster or slower.

I've committed a change, which allows user of this library to change this option:
```php
$mailbox->getImapSearchOption(); // Default is SE_UID
$mailbox->setImapSearchOption(SE_FREE); // Note: Parameter must be a constant!
$mailbox->getImapSearchOption(); // We changed it, so it will return SE_FREE
```

The new functions will be included in the next release.
