### ISSUE TITLE
Error imap_mime_header_decode

### ISSUE THREAD

**Issue by StApostol** [barbushin/php-imap#202]
on one of the letters I have an error with the decoding of the header subject
serverEncoding = UTF-8
Subject in  Thunderbird: HÖPLERS Weinclub zum Verschenken
`
Subject: =?UTF-8?B?SMOWUExFUlMgV2VpbmNsdWIgenVtIFZlcnNjaGVua2Vu=?=
`
This subject return fatal error
https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L710 
count($elements) = 1, but $elements[$i] is null

**Comment by barbushin** [comment]
What is error text?

**Comment by StApostol** [comment]
ErrorException: Trying to get property of non-object in /var/www/wein-plus/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php:710

**Comment by mbaric** [comment]
Hello @barbushin and @StApostol , I am pulling and syncing emails for the client and I am having the same problems. I am using Laravel 5.7. 

I traced it down with PhpStorm to...

`vendor/php-imap/php-imap/src/PhpImap/Mailbox.php line 706` method `protected function decodeMimeStr($string, $toCharset = 'utf-8') {`

error is: `Throwable error: Invalid argument supplied for foreach()`

Since I don't particularity care about `subject` field I created a try/catch and I return to `N/A`:

```
protected function decodeMimeStr($string, $toCharset = 'utf-8') {
        try {
            $newString = '';
            foreach (imap_mime_header_decode($string) as $element) {
                if (isset($element->text)) {
                    $fromCharset = !isset($element->charset) || $element->charset == 'default' ? 'iso-8859-1' : $element->charset;
                    $newString .= $this->convertStringEncoding($element->text, $fromCharset, $toCharset);
                }
            }
            return $newString;
        } catch (\Throwable $t) {
            return 'N/A';
        }
    }
```

Now subject has something similar like @StApostol had above 

`Subject: =?UTF-8?B?SMOWUExFUlMgV2VpbmNsdWIgenVtIFZlcnNjaGVua2Vu=?=`

Now either we fix this or I stay at the current version that I have downloaded, because I don't want this to be overwritten on next composer update. Please advise the best approach on this. Or if you need more info.

P.S. Thank you for creating this imap wrapper library @barbushin
