### ISSUE TITLE
Assumed '.' Delimiter

### ISSUE THREAD

**Issue by mrforsythexeter** [barbushin/php-imap#213]
The functions like "createMailbox" and related assume the path separator is '.' however this shouldn't be assumed, it should be read from getMailboxes.

**Comment by barbushin** [comment]
Is there any suggestion or question?

**Comment by mrforsythexeter** [comment]
The suggestion was to get the delimiter from getMailBoxes.

Im sorry I don't have time to create a merge request at the moment.

I guess I would get the delimiter as soon as a connection it made for the imapPath. It "Shouldn't" change the delimiter based on the folder depth you are in (server defined), so assign a new pathDelimiter property to the object, and then just use that moving forward.

Sorry, I don't have time to look at this at the moment. I can try and circle back around to this later.

**Comment by aymanrb** [comment]
I would agree with @mrforsythexeter regarding the hardcoded (assumed value). All my newly created directories were set with a (dot) prefix due to this.

I just didn't want to call a getMailBoxes() after connection as suggested and added a setter method allowing the developer to set his own value if it doesn't match the default one.

```
$mailbox = new Mailbox($imapPath,  $username, $password);                               
$mailbox->setPathDelimiter('/'); 
```

The reason behind this is that getMailBoxes() results are strongly dependent on the search parameter and initial imapPath provided and is not really meant for the prefix return.

**Comment by Sebi94nbg** [comment]
The path delimiter can be set dynamically now:
```
$mailbox->setPathDelimiter('/');
```

See lines [47-53](https://github.com/barbushin/php-imap/blob/master/src/PhpImap/Mailbox.php#L47-L53).
