### ISSUE TITLE
error in getMail:  "Trying to get property of non-object"

### ISSUE THREAD

**Issue by creativefctr** [barbushin/php-imap#222]
Hi,
Whwn I try to use getMail, on some ids I get:
"Trying to get property of non-object" on this line inside initMailPart:
```
if($partStructure->encoding == 1) {
        $data = imap_utf8($data);
}
```
Any idea why this is happening?
thanks

**Comment by samwilson** [comment]
The real error may be being hidden by the `@` suppressor in Mailbox::imap()

It seems that some errors are raised as PHP warnings instead of being captured for `imap_errors()`, e.g. "Warning: imap_fetchheader(): Bad message number in .../vendor/php-imap/php-imap/src/PhpImap/Mailbox.php on line 822".

**Comment by samwilson** [comment]
Note also that you have to use the mail UID, not the sequence ID, with getMail(). e.g.

```php
		$mailId = 1;
		$uid = $mailbox->imap('uid', [ $mailId ]);
		$mail = $mailbox->getMail($uid);
```

**Comment by Sebi94nbg** [comment]
Closing this as it can't be reproduced and it's already very old. Feel free to open a new issue, if you're still facing this issue.

**Comment by samwilson** [comment]
I think the only actionable thing here could possibly be to handle PHP warnings raised by
https://github.com/barbushin/php-imap/blob/8c7c01100539cc3efcbec2e0545469d32ec4bc3f/src/PhpImap/Mailbox.php#L935
