### ISSUE TITLE
Question Regarding Email Fetching 

### ISSUE THREAD

**Issue by Tekrajs** [barbushin/php-imap#231]
Is there any way I can track to know which mails were fetched and which were remining? Or the newest mail in the inbox ? If so please let me know. I would be really greatful. Thanks. :)

**Comment by Sebi94nbg** [comment]
Not really. By default, the function `getMail($mailId, $markAsSeen = true)` will mark all fetched emails as "seen" / "read", so you could expect, that those emails were fetched by `php-imap` and all unread / unseen emails are the remaining ones.

The problem is: If someone opens or marks a new email, which wasn't fetched by `php-imap` yet, it may don't get parsed as you only fetch 'Unseen' emails.

One solution would be the following:

1. Fetch all emails using `php-imap` (not only unseen, even seen)
2. Parse all emails and insert the unique `messageId` of each email into a database table
3. While parsing emails, check, if you have already checked this email or not by comparing it with your database table

You may limit the IMAP fetch to all emails from the last month for example. Then you also could cleanup your database table by deleting all rows, which are older then one month.
