### ISSUE TITLE
Add JMAP support (as an alternative to IMAP + SMTP, and later to CardDAV/CalDAV)

### ISSUE THREAD

**Issue by marclaporte** [barbushin/php-imap#237]
"JMAP is intended to be a new standard for email clients to connect to  
mail stores. It therefore intends to primarily replace IMAP + SMTP  
submission. It is also designed to be more generic such that it can be  
extended with contacts, calendars in the future (replacing  
CardDAV/CalDAV). It does not replace MTA-to-MTA SMTP transmission."

http://jmap.io/

You may wonder "Who uses or supports it?"

Cyrus IMAP and Apache James are the notable ones here:  
http://jmap.io/software.html
https://cyrusimap.org/imap/developer/jmap.html

OpenPaaS is an open source Entreprise Social Platform which is led by  
LINAGORA (which has more than 150 employees)
https://linagora.com/
http://www.open-paas.org

OpenPaaS is using Apache James. And you can see JMAP used in the code:
https://github.com/linagora/openpaas-esn/search?utf8=%E2%9C%93&q=jmap&type=

In this video: https://www.youtube.com/watch?v=2QZIi3EO6rQ , Benoit  
Tellier explains why they decided to invest in James and JMAP (among  
other things). LINAGORA has 5 full time employees which are devoted to  
the project.

Why LINAGORA picked JMAP:
https://medium.com/linagora-engineering/you-cant-do-imap-in-the-browser-can-you-208838b0ba17
https://medium.com/linagora-engineering/openpaas-newsletter-march-2018-c0a3e469e83e
https://medium.com/linagora-engineering/openpaas-is-out-773704eadfbc

FastMail started this initiative:
"JMAP is FastMail's protocol with the warts removed. We leverage  
existing standards like HTTP, JSON, and native push channels on  
platforms which have them - making it easy for developers to work with."
https://blog.fastmail.com/2017/12/08/fastmail-at-ietf/
https://blog.fastmail.com/2016/12/22/cyrus-development-and-release-plans/
https://blog.fastmail.com/2016/12/12/why-we-contribute/
https://blog.fastmail.com/2016/12/09/jmap-test-suite/
https://blog.fastmail.com/2015/12/23/the-jmap-momentum-builds/
https://blog.fastmail.com/2015/08/11/an-open-source-jmap-proxy-javascript-library-and-webmail-demo/
https://blog.fastmail.com/2014/12/23/jmap-a-better-way-to-email/

Roundcube Next also plans to support JMAP.
https://github.com/search?q=org%3Aroundcube-next+jmap&type=Code

Thanks!

**Comment by nickl-** [comment]
Since this library mainly focuses an making the [php imap extension](https://www.php.net/manual/en/book.imap.php) and functions easier to use I can't imagine it would consider any other protocols. If you've actually tried using the extension functions directly you'll know what I mean. It has a very specific process for doing things which is at the core of this library. You'll be better off starting over with a new client for JMAP rather than trying to include anther protocol here.

My 2c...

**Comment by Sebi94nbg** [comment]
I fully agree to @nickl- feedback. This library is only made to make it easier to handle PHP "imap_" functions.

`php-imap` does not provide any functionalities for SMTP or even CardDAV / CalDAV.

JMAP is also its own library, so it makes no sense to integrate one library into another. This only increases the support effort, because if you change the JMAP library, everything in `php-imap` would have to be changed as well.

You need to decide, if you want to use `php-imap` or `JMAP`. This decision depends on your requirements. For myself, `php-imap` is perfect as I only need the IMAP functionalities - `JMAP` would be to oversized for this as it also provides those other mentioned features.
