### ISSUE TITLE
UTF7 Encoding fail with french accent when using imap_sort

### ISSUE THREAD

**Issue by fpiccinali** [barbushin/php-imap#263]
In MailBox::imap there is `$arg = imap_utf7_encode($arg);` (line 848)

When we call mailbox->sort(), this encoding fail search with french accents. 

if we disconnect this line, it works.

It could be related to this one to : https://github.com/barbushin/php-imap/pull/212
Maybe, we could check args for encoding ?

**Comment by Sebi94nbg** [comment]
This issue seems to be fixed. I can sort any kind of email by
- SORTDATE - message Date
- SORTARRIVAL - arrival date
- SORTFROM - mailbox in first From address
- SORTSUBJECT - message subject
- SORTTO - mailbox in first To address
- SORTCC - mailbox in first cc address
- SORTSIZE - size of message in octets

...without any problem. The sorting was correct after each test and no errors / notices or warnings occured.

Those emails, which I used to test had ASCII, non-ASCII and special characters in their subject and body (message). Below a few examples:
- mountainguan测试
- Inline image & attachment incl. UTF-8 characters like ö#Ü&
- #263: Sorting! tréma ë, ï, ü, à, è, ù, â, ê, î, ô, û, é, cédille Ç
- PHP-IMAP Test on outlook.office365.com
