### ISSUE TITLE
Rediffmail references in header shows plus as a space

### ISSUE THREAD

**Issue by avinash403** [barbushin/php-imap#277]
STEPS TO REPRODUCE:
Send an email in gmail with cc as a rediffmail account. Now reply with the rediffmail account. The `+` sign in in_reply_to show as a space. See the below screenshots for reference
![screen shot 2019-01-28 at 4 21 44 pm](https://user-images.githubusercontent.com/31030044/51831877-39a85b00-2319-11e9-8c08-90a7c2ffac51.png)
![screen shot 2019-01-28 at 4 22 04 pm](https://user-images.githubusercontent.com/31030044/51832066-b20f1c00-2319-11e9-842d-dca635e9bb8c.png)

**Comment by Sebi94nbg** [comment]
Allowed characters are: `::alpha::|::digit::|[!#$%&'*+-/=?^_`{}|~.]` (RFC2822)
Reference: https://stackoverflow.com/questions/594330/constraints-on-smtp-message-id

So, there should be no space at all. I'll try to reproduce this.

@avinash403: Do you have any code samples, which you used in order to debug this faster?

**Comment by Sebi94nbg** [comment]
I've added some PHPUnit tests to make sure, that this does not happen. All tests were successful. (See above reference.)

Closing this as there is no bug or issue in `php-imap`.

Feel free to add comments to this issue, when you still think, that something is not working as expected.
