### ISSUE TITLE
[ Question ] Permanently deleting outlook.live.com email

### ISSUE THREAD

**Issue by D4V3M0NK** [barbushin/php-imap#356]
- PHP IMAP version: [e.g. 3.0.26]
 - PHP Version: [e.g. 7.2.19]
 - CLI

I would like to imitate the ability to permanently delete an email within an outlook.live.com account. At the moment, using a browser, this is completed by:

1. Delete the item from whatever folder (by default and for the purposes of this post, we'll assume it goes into Deleted Items)

1. Select **Deleted Items**

1. Click the **Delete** Icon on the respective email

1. Select **Recover items deleted from this folder**

1. From this page, **select** the respective email

1. Select **Delete** from the top of the page

It's gone for good, or as close as one will ever get to fully deleting the email.

What I want to achieve is the same thing with PHP-IMAP. Stages 1 - 3 are pretty simple and are working perfectly, but my problem lies in finding the "Recovery folder" that's mentioned in Step 4.

When I use $mailbox->getMailboxes('*') there's no recovery folder listed, so I can't then use $mailbox->switchMailbox('RECOVERY_FOLDER'); to go into that folder, get the IDs of the mail in order to permanently delete it.

$mailbox->expungeDeletedMails() doesn't appear to do anything either.

I appreciate that this is most probably an Outlook thing and therefore isn't a bug, or feature of this rather wonderful library, and I've already posted an SO article upon it, but wondered if the developers had come across this before and had some insight into how to resolve it?

**Comment by Sebi94nbg** [comment]
I'll check this out tomorrow and provide you an example code.

**Comment by Sebi94nbg** [comment]
**General Information**
First of all, you need to add the "Delete" flag to your mail(s) which you want to delete.

As soon as you have marked all mails, which you want to delete, you only need to call [imap_expunge()](https://www.php.net/manual/de/function.imap-expunge.php) or you simply close the IMAP connection with the option `CL_EXPUNGE`.

Using the `php-imap` library your code should look like this to permanently delete a mail:
```php
$mailbox = new PhpImap\Mailbox(
	'{imap.gmail.com:993/imap/ssl}INBOX', // IMAP server and mailbox folder
	'some@gmail.com', // Username for the before configured mailbox
	'*********', // Password for the before configured username
	__DIR__, // Directory, where attachments will be saved (optional)
	'US-ASCII' // Server encoding (optional)
);

try {
	// Search in mailbox folder for specific emails
	// PHP.net imap_search criteria: http://php.net/manual/en/function.imap-search.php
	// Here, we search for "all" emails
	$mails_ids = $mailbox->searchMailbox('ALL');
} catch(PhpImap\Exceptions\ConnectionException $ex) {
	echo "IMAP connection failed: " . $ex;
	die();
}

// Loop through all emails
foreach($mails_ids as $mail_id) {
	// Just a comment, to  see, that this is the begin of an email
	echo "+------ P A R S I N G ------+\n";

	// Get mail by $mail_id
	$email = $mailbox->getMail(
		$mail_id, // ID of the email, you want to get
		false // Do NOT mark emails as seen
	);

	echo "from-name: " . (isset($email->fromName)) ? $email->fromName : $email->fromAddress;
	echo "from-email: " . $email->fromAddress;
	echo "to: " . $email->to;
	echo "subject: " . $email->subject;
	echo "message_id: " . $email->messageId;

	// Add "Delete" flag to mail
	// This does actually not delete the mail
	$email->deleteMail($mail_id);
}

// Delete all marked mails
$mailbox->expungeDeletedMails();
```

**Outlook Specific Information**
Microsoft provides the ability to restore even permanently deleted items (mails and folders) in some cases:

> When you accidentally delete an email message in Outlook on the web you can recover the message if it's still in your Deleted Items folder. In some cases, you can even recover items after the Deleted Items folder is emptied.
> 
> You can also recover a deleted folder (with all of its messages) if it's still in your Deleted Items folder. Unfortunately, you can't recover a folder that's been permanently deleted. But you can use the steps in this topic to recover messages that were in a folder when it was permanently deleted.

_Source: https://support.office.com/en-us/article/recover-deleted-email-messages-in-outlook-on-the-web-a8ca78ac-4721-4066-95dd-571842e9fb11_

Since this is a feature from Microsoft and not an issue or bug from the PHP IMAP functions, you need to find a solution to disable this feature in Outlook. There was a way to disable this feature, but I couldn't find this setting in my Outlook account: https://ccm.net/faq/26544-how-to-disable-message-recovery-on-outlook

So you might want to contact the Microsoft Outlook support to disable this feature, if it's really necessary.

---
Refs:
- https://support.office.com/en-us/article/recover-deleted-email-messages-in-outlook-on-the-web-a8ca78ac-4721-4066-95dd-571842e9fb11
- https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-in-hotmail-disable-recover-deleted-items/ba00f507-4f9c-40e9-9aa2-d0b0fe88cd5f
- https://ccm.net/faq/26544-how-to-disable-message-recovery-on-outlook
- https://stackoverflow.com/questions/18656363/imap-delete-and-imap-expunge-doesnt-permanently-delete
- https://www.electrictoolbox.com/delete-message-php-imap/
