### ISSUE TITLE
Checking for attachments without downloading message

### ISSUE THREAD

**Issue by D4V3M0NK** [barbushin/php-imap#363]
- PHP IMAP version: 3.0.26
 - PHP Version: 7.2.19
 - Type of execution: CLI

Are there any provisions in php-imap to ascertain if a message has an attachment, without actually downloading the message? I see that the native PHP imap_fetchstructure outlined [here](https://www.electrictoolbox.com/extract-attachments-email-php-imap/) shows the process of diving through the object.  From what I've seen, all examples of php-imap processing attachments are precluded with downloading the message first, and of course this makes perfect sense in actually obtaining the attachment, but I can't see anywhere (including the wiki examples) that shows whether or not a message has an attachment, before actually downloading it.

**Comment by Sebi94nbg** [comment]
You mean like in this example here? https://github.com/barbushin/php-imap/blob/master/examples/get_and_parse_all_emails_without_saving_attachments.php

```php
echo "mail has attachments? ";
if ($email->hasAttachments()) {
        echo "Yes\n";
} else {
        echo "No\n";
}
```

**Comment by D4V3M0NK** [comment]
No - you may notice that the code clip you've posted the script has already retrieved the email:

`$email = $mailbox->getMail($mail_id,false);`

**Comment by Sebi94nbg** [comment]
This doesn't seems to be possible, since you need fetch somehow the emails content to check, what it has and what not.

Stackoverflow confirms this: https://stackoverflow.com/questions/9939463/php-imap-check-if-email-has-attachment

You could try this workaround: Analyze the mails structure using `imap_fetchstructure`. See https://www.php.net/manual/de/function.imap-fetchstructure.php#42656
