### ISSUE TITLE
[QUESTION] $mailbox->getMail is too Slow

### ISSUE THREAD

**Issue by mafangel** [barbushin/php-imap#371]
**Environment (please complete the following information):**
 - PHP IMAP version: LAST
 - PHP Version: 7+

$mailbox->getMail work too slowly (near 1 seconds to fetch each mail)
so for 15 letters i spend 15 sec.

**Comment by Sebi94nbg** [comment]
How did you measure this, @mafangel ?

How fast this library can fetch and get your emails depends on the used mail server, the mail servers performance, your connection to this mail server and your servers performance.

Since the `php-imap` library has currently some duplicate pieces of code, it's indeed a bit slower, than it should be, but changing this wouldn't improve this that much. It's most of the time an issue of the other mentioned points.

**Comment by mafangel** [comment]
$start = microtime(true); 
$mailbox->getMail (................)
echo 'time for getting mail Is: '.(microtime(true) - $start).'  sec.';

I use Google mail. 
Just for
UNANSWERED SINCE "01-Aug-2019" TO "myMailBox@mail.box"

8 letters = more than 8 secs

**Comment by Sebi94nbg** [comment]
Thanks, I've just measured the same with the office365 mail server.

Used code:
```php
<?php
        require_once __DIR__ . '/vendor/autoload.php';
        use PhpImap\Mailbox;
        use PhpImap\Exceptions\ConnectionException;

        $mailbox = "{outlook.office365.com:993/imap/ssl}";
        $mailbox_username = "mailbox@outlook.com";
        $mailbox_password = "verySecretPassword";

        echo "Trying to connect to '$mailbox'...\n";

        $mbox_connection = new Mailbox($mailbox, $mailbox_username, $mailbox_password, __DIR__ . '/files/');

        try {
                $mbox_connection->setServerEncoding('US-ASCII');
        } catch(InvalidParameterException $ex) {
                echo "Setting server encoding failed: " . $ex->getMessage() . "\n";
                die();
        }

        $mbox_connection->setAttachmentsIgnore(false);

        if(!$mbox_connection->getAttachmentsIgnore()) {
                echo "Save files in: " . $mbox_connection->getAttachmentsDir() . "\n";
        }

        try {
                $mailsIds = $mbox_connection->searchMailbox('ALL');
        } catch(ConnectionException $ex) {
                echo "IMAP connection failed: " . $ex->getMessage() . "\n";
                die();
        }

        if(empty($mailsIds)) {
                echo "No emails found!\n";
                $mbox_connection->disconnect();
                die();
        }

        echo "Found " . count($mailsIds) . " email(s)...\n";

        $start = microtime(true);

        foreach($mailsIds as $mailId) {
                echo "+------ P A R S I N G ------+\n";

                $email_content = $mbox_connection->getMail($mailId, false);
        }

        echo 'time for getting mail Is: '.(microtime(true) - $start).' sec.';
```

Result with the `ALL` filter:
```bash
$ php outlook.php
Trying to connect to '{outlook.office365.com:993/imap/ssl}'...
Save files in: /home/sebastian/github/php-imap/files
Found 19 email(s)...
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
time for getting mail Is: 3.0901038646698 sec.
```

So 19 emails in nearly 3 seconds.

Same code, with a similar filter like you used: `UNANSWERED SINCE "01-May-2019" TO "mailbox@outlook.com"`
```bash
$ php outlook.php
Trying to connect to '{outlook.office365.com:993/imap/ssl}'...
Save files in: /home/sebastian-kraetzig/github/php-imap/files
Found 19 email(s)...
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
+------ P A R S I N G ------+
time for getting mail Is: 4.6154909133911 sec.
```

Also only 4.6 seconds for 19 emails.

Looks like as the Google mail server is not that fast.

So on average it took about 0.2 seconds per e-mail.

> May be i can use some method for fetching all mails for one call?
My above code is already fetching all emails in one call. There is no other solution, since the PHP IMAP library does not offer any better feature.

`searchMailbox()` is getting all matching mail IDs. After this, you need to get the structure of each email ID, parse it's structure and decode / convert everything etc. - this does `getMail()`.

In your case, you either have a worm in the source code that slows it down like this, or the Gmail server is just slow.

**Comment by mafangel** [comment]
Thank you!
Refreshing list of 10 letters - slows down my system (((
But seems it's my problem (sorry my english)
