### ISSUE TITLE
[BUG] Wrong charset, conversion from `'ks_c_5601-1987' to 'UTF-8//IGNORE'` is not allowed

### ISSUE THREAD

**Issue by dixstonz3** [barbushin/php-imap#382]
**Environment (please complete the following information):**
 - PHP IMAP version: 3.0.30
 - PHP Version: 7.1.32
 - Type of execution: Web Server

**Describe the bug**

iconv(): Wrong charset, conversion from `'ks_c_5601-1987' to 'UTF-8//IGNORE'` is not allowed	ezsystem.com	/var/www/html/live/vendor/php-imap/php-imap/src/PhpImap/Mailbox.php	1227

**To Reproduce**
See the code below and the attached email.

The used code:
```php
$mailbox = new \PhpImap\Mailbox($imapPath, $login, $password, sys_get_temp_dir());
$mail = $mailbox->getMail($mailId);
var_dump($mail->textPlain);
```
[RTA Daily Inventory.txt](https://github.com/barbushin/php-imap/files/3594711/RTA.Daily.Inventory.txt)

Here is the suggested fix (it's working for me):

https://github.com/barbushin/php-imap/issues/208#issuecomment-350242864

**Comment by Sebi94nbg** [comment]
I've not implemented the provided fix from your mentioned comment since this is kinda messy.

Instead, this library tries to convert the string and if it fails, it will return the original string.

Released in version [3.0.31](https://github.com/barbushin/php-imap/releases/tag/3.0.31).

Closing this issue for now. If it doesn't solve your issue, please come back and we'll check, if we can implement the mentioned fix in a somehow better way.
