### ISSUE TITLE
[BUG] Undefined property: stdClass::$host

### ISSUE THREAD

**Issue by royfandi** [barbushin/php-imap#404]
**Environment:**
 - PHP IMAP version: 3.0.32
 - PHP Version: 7.2
 - Type of execution: FPM

**Describe the bug**
When trying to read an emails without TO recipients, the library gives the following error: 
`Undefined property: stdClass::$host`

Probably related with: 
 - https://github.com/barbushin/php-imap/issues/119
 - https://github.com/barbushin/php-imap/issues/359

**To Reproduce**
Send an email without TO recipients and the set the email addresses into the CCO. Read the email with the IMAP library.

**Expected behavior**
Expected empty TO when reading email.

**The used code:**
```
$mailbox->getMail($emailId);
```

**Comment by Sebi94nbg** [comment]
I can not reproduce this issue by simply getting the mail using `$mailbox->getMail($emailId);`.

I've sent an email with the following values:
- To: <empty / not set>
- Cc: php-imap [AT] outlook [DOT] com
- Bcc: <empty / not set>
- Subject: GitHub Issue #404
- Text / Body / Content: TO should be empty and not throw any error / warning.

Can you please show us your code and the error / warning output, which shows this `undefined property` message?

Since I can't reproduce this issue, I've added some extra checks to avoid such warnings. See referenced commit.

**Comment by Sebi94nbg** [comment]
I've released a new version with those additional checks. Please test it and let me know, if this solved your problem.

**Comment by royfandi** [comment]
Hello, on Monday I will try the new version and if it doesn't fix the issue, I will include the stack trace (I forgot to include it in the original message).

Thank you.

**Comment by royfandi** [comment]
Hello!, Today I tested the new release and it fixed the issue! Now it is working flawless.ç
Thank you !
