### ISSUE TITLE
how to fix : Notice: iconv(): Detected an illegal character in input string in 

### ISSUE THREAD

**Issue by ychoucha** [barbushin/php-imap#46]
Hello i have this error ervry time how i can fix it please : 

'''Notice: iconv(): Detected an illegal character in input string in /var/www/Pr/lib/ImapMailbox.php on line 426 Notice: iconv(): Detected an illegal character in input string in /var/www/Pr/lib/ImapMailbox.php on line 426 Notice: iconv(): Detected an illegal character in input string in /var/www/Pr/lib/ImapMailbox.php on line 426 

'''

**Comment by menzo** [comment]
I have the same issue. Is there any news with this? 
I've silenced the iconv (with @) in line 473, but a permanent fix would be better.

**Comment by barbushin** [comment]
No ideas. May be somebody can do good proper pull request?

**Comment by aymanrb** [comment]
Thanks @barbushin and @georaldc for the latest implementation. Seemed to be the prettiest was to use `mb_convert_encoding` yet still keep `iconv` for other installations.

Now since you already made the check that the `from` and `to` encoding charsets are different then I would personally prefer to remove the mb_convert_encoding usage since it lacks support to a bunch of encodings (see supported ones here: http://php.net/manual/en/mbstring.encodings.php)

It keeps failing to return the correct decoded string for things like "windows-1256" and "GB2312"

**Comment by georaldc** [comment]
@aymanrb I see. That might be why others are are still running into issues. Are you suggesting to just drop ```mb_convert_encoding``` and use ```iconv```?

**Comment by aymanrb** [comment]
Yes, so far that worked for me, initially it caused issues cus the '//ignore' flag was not used and cuz we sometimes asked it to convert utf-8 to utf-8  and that failed resulting in an empty string.

Now with the double conditions we have there iconv should be more efficient (at least my test results says that)

**Comment by TTouka** [comment]
Thanks for implementation of my suggestion.

Dropping `mb_convert_encoding` is not good idea.
`//IGNORE` flag affects only output, so when `iconv` received broken string, it cannot convert the string.

So, using both functions may solve those issues:

1. Convert given string with `@iconv()`.
2. When `iconv()` returns `false`, try to convert that string with `mb_convert_encoding()`.
3. When `iconv()` returns `string`, finish converting.

**Comment by aymanrb** [comment]
Ok that would be a better implementation

**Comment by shdinx** [comment]
Adding to this whole converting issue - you probably should consider to silence mb_convert_encoding as well.

I have a string which is in a Semitic language ( WINDOWS-1256 ) and you try to convert it with mb_convert_encoding as long as we have loaded the mbstring extension.

However, mb_convert_encoding does not support WINDOWS-1256 as seen here: http://php.net/manual/en/function.mb-list-encodings.php

iconv() on the other hand does: http://www.gnu.org/software/libiconv/

Based on this RFC document it is a valid charset: http://www.iana.org/assignments/character-sets/character-sets.xhtml

We need to manage this case or otherwise we will end up with the warning from mb_convert_encoding.

A possible solution could be this mapping: https://rayed.com/wordpress/wp-content/upload/lib.utf2win.php.txt

**Comment by barbushin** [comment]
@shdinx How do you think, may be we can just do something like this: 

`$convertedString = @mb_convert_encoding($string, $toEncoding, $fromEncoding) ? : @iconv($fromEncoding, $toEncoding . '//IGNORE', $string);`

?
