### ISSUE TITLE
Email UID gets changed when moving to different folder

### ISSUE THREAD

**Issue by yogeshsaroya** [barbushin/php-imap#483]
I found that UIDs of emails are changed if they are moved from one folder to another. Even if moved back to the same folder. IMAP uid is not unique on different folders. It gets changed when you move email from one folder to another.

suppose I copied email from Inbox to MySQL database including unseen emails. The same email account is being used with outlook/email client and unseen emails moved to another folder (Folder Client). Now at web-app ( PHP IMAP ) how to mark that email as seen? on move, UID already gets changed.

How to manage this thing? How to sync email? I can not sync all folders and emails all the time, like if have 50K emails.

**Comment by bapcltd-marv** [comment]
I've been giving this one some thought but can't quite test the theory as my particular use-case doesn't involve a lot of message moving.

* UID changes are unavoidable due to how the underlying php extension works
* creating unique hashes of messages would require syncing the messages anyway
* diffing a folder's before & after UIDs to update the database is a bit of a fragile solution as in some unrelated  task new emails might arrive or messages might be deleted during the move operation, etc.

If you're *reasonably certain* that emails won't be added/removed while you're moving mails then:
1) your db schema should track row id separate from the email UID
2) if there's 1 new UID in the destination folder *and* the original UID is not in the source folder *and* you're reasonably certain that nothing else has changed, update the UID field in your mysql database.

Alternatively, pester me to dig out the filesystem cache I built on top of php-imap ages ago so messages that don't get moved don't have to get redownloaded.
