### ISSUE TITLE
Login via Browser Alert

### ISSUE THREAD

**Issue by niloyniloy** [barbushin/php-imap#87]
I installed the code but the found the error . 
Notice: Unknown: [ALERT] Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure) (errflg=1) in Unknown on line 0
I

can u please tell me , why I getting this error ?

**Comment by barbushin** [comment]
May be it's because there is two-factor authorization enabled for your Google account?

**Comment by nicanaca0** [comment]
Gmail has some extra settings on the account which you can access at this URL: https://www.google.com/settings/security/lesssecureapps

It's due to the PHP IMAP access being classed as not-secure by Google. Once you change the value for the account using the link above the PHP Mailbox will return mail as it's supposed to.

(had this issue today)
